development:
      host: localhost
      adapter: mysql
      database: fedena_dev
      port: 3306
      username: root
      password: 

test: &test
      host: localhost
      adapter: mysql
      database: fedena_test
      port: 3306
      username: root
      password: 

production:
      host: localhost
      adapter: mysql
      database: fedena_prod
      port: 3306
      username: root
      password: 
cucumber:
  <<: *test
